export const appActionTypes = {
  FETCH_ALL_STORIES_START: 'FETCH_ALL_STORIES_START',
  FETCH_ALL_STORIES_SUCCESS: 'FETCH_ALL_STORIES_SUCCESS',
  FETCH_ALL_STORIES_FAILURE: 'FETCH_ALL_STORIES_FAILURE',
};
