export const appActionTypes = {
  FETCH_ALL_STORIES_START: 'FETCH_ALL_STORIES_START',
  FETCH_ALL_STORIES_SUCCESS: 'FETCH_ALL_STORIES_SUCCESS',
  FETCH_ALL_STORIES_FAILURE: 'FETCH_ALL_STORIES_FAILURE',

  FETCH_STORY_BY_ID_START: 'FETCH_STORY_BY_ID_START',
  FETCH_STORY_BY_ID_SUCCESS: 'FETCH_STORY_BY_ID_SUCCESS',
  FETCH_STORY_BY_ID_FAILURE: 'FETCH_STORY_BY_ID_FAILURE',

  SEARCH_STORY: 'SEARCH_STORY',
};
